#V12
# https://docs.github.com/en/actions/concepts/runners/github-hosted-runners
name: Deploy Distribution
# on: push
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: |
          echo "Cloning repository..."
          echo "github: ${{ toJson(github) }}"
          git clone https://github.com/${{ github.repository }}.git myfiles
          cd myfiles
