#V26
# https://docs.github.com/en/actions/concepts/runners/github-hosted-runners
# https://github.com/marketplace/actions/checkout
# https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
# https://github.com/marketplace/actions/setup-node-js-environment
# https://github.com/marketplace/actions/cache
# https://github.com/marketplace/actions/upload-a-build-artifact
# https://github.com/marketplace/actions/download-a-build-artifact
name: Filters
# on: [push, workflow_dispatch]
on:
  push:
    branches:
      - main
      - "feature/**"
    paths-ignore:
      - README.md
      - ".github/workflows/*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Setup node and install dependencies
        uses: ./.github/actions/setupnode
      - name: Run tests
        run: npm test

  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Setup node and install dependencies
        uses: ./.github/actions/setupnode
      - name: Build
        run: npm run build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v5
        with:
          name: dist-files
          path: dist
      - name: Deploy Dist
        run: |
          ls dist
          echo "Deploying Dist"
