#V6
name: Deploy Distribution
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup credentials to access private repositories
        run: git config --global url.https://${{ secrets.MY_PAT }}@github.com/.insteadOf https://github.com/
      - name: Get Code
        run: |
          echo "Cloning repository..."
          echo "github: ${{ toJson(github) }}"
          git clone https://github.com/${{ github.repository }}.git myfiles
          cd myfiles
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Build Docker Image
  #       run: docker build -t my-app .
  #     - name: Deploy to Server
  #       run: ssh user@server "docker run -d my-app"
